### ISSUE TITLE
problem in npm install

### ISSUE THREAD

**Issue by MehdiElMellali** [bredmor/simple-discord-js-bot#2]
npm ERR! No versions available for weirdapi.js

**Comment by bredmor** [comment]
Hi @MehdiElMellali - I don't see that package anywhere in our dependency tree. Regardless, I've updated discord.js to version 12 in the most recent commit. Go ahead and delete your `node_modules` folder and run `npm install` again - hopefully you'll be good to go.

**Comment by bredmor** [comment]
@MehdiElMellali did this resolve your issue?

**Comment by bredmor** [comment]
Closing this issue as there has been no response.
