### ISSUE TITLE
Help.js

### ISSUE THREAD

**Issue by ghost** [bredmor/simple-discord-js-bot#5]
When I run help.js in my console, it gives this error. Why? How do I fix it? Thanks in advance
![image](https://user-images.githubusercontent.com/67627239/101510093-7cb8c800-399f-11eb-9efc-a4444a5c6098.png)

**Comment by ghost** [comment]
When I run help.js in my console, it gives this error. Why? How do I fix it? Thanks in advance. Also, if possible, please have a support server to help newbies like me. Thanks again!!
![image](https://user-images.githubusercontent.com/67627239/101510213-a671ef00-399f-11eb-9920-4bc650ec98b4.png)

**Comment by bredmor** [comment]
Why are you running help.js in your console? This is an include file used to define a command, the only thing you should be running is index.js - this is explained in the README.

**Comment by ghost** [comment]
Hello,
I'm sorry for the misunderstanding, but I made another bot, my friend copied this help command and gave it to me. For testing purposes, I tried for this, and its not working. I use a package called `WOKCommands` as my Command Handler. It shows the above error. 
Thanks for the reply !!

**EDIT:-** Is there any other `Command Handler` that you recommend, which checks through the Commands and its subfolders. When I use the Command Handler in the Discord.js Guide or this one, my commands folder is very messy, and doesn't look good.

Thanks again !!

**Comment by bredmor** [comment]
I think you're trying to combine multiple packages together. The commands in this codebase aren't meant to be used with any other type of bot or command handling package, they're just made for this exact bot structure.

**Comment by ghost** [comment]
Ok, so, what can I change to make it work with the `WOKCommands` Package.

Thanks in advance!!

**Comment by bredmor** [comment]
That's something you'll have to figure out for yourself, or ask the developers of that package. I've never used it.
