### ISSUE TITLE
Npm install.

### ISSUE THREAD

**Issue by davqt** [bredmor/simple-discord-js-bot#6]
When i run "npm install" is says weirdapi.js has no versions available. I don't know how it happens, but it is. I've tried running it multiple times. Help me please.

**Comment by ghost** [comment]
Give me the **exact error**

**Comment by bredmor** [comment]
I've seen a couple people come up with this issue, but I've never been able to reproduce it.

`weirdapi` does not exist anywhere in our dependency graph.

I'm going to close this issue for now, but if you want to follow up with your exact commands and output at some point, I'll be happy to come back and work through the issue with you.
